version: 2
jobs:
  install:
    docker:
      - image: circleci/node
    steps:
      # source code
      - restore_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      # node modules
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node
    steps:
      - restore_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}e
      - run:
          name: test
          command: npm test
  lint:
    docker:
      - image: circleci/node
    steps:
      - restore_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: lint
          command: npm run lint
workflows:
  version: 2
  test_and_lint:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
          filters: 
            branches: 
              only: master